---
- hosts: all
  become: true
  roles:
    - users
    - sysutils
    - { role: geerlingguy.java, when: "'ansible' in inventory_hostname" }
    - { role: haproxy, when: "'haproxy' in inventory_hostname" }
    - { role: webserver,  when: "'web' in inventory_hostname" }
    - { role: javaone_config_update, when: "'web' in inventory_hostname" }

